### ISSUE TITLE
presentation review

### ISSUE THREAD

**Issue by AbelNavarro** [aspiers/compute-ha-presentation#1]
http://aspiers.github.io/compute-ha-training/#/SOC-demo
video not available

http://aspiers.github.io/compute-ha-training/#/starting-point
screenshot and text outside slide template

http://aspiers.github.io/compute-ha-training/#/test-vm
text outside slide template

http://aspiers.github.io/compute-ha-training/#/shared-storage
two slides merged, must split "recovery monitor" and "shared storage"

Section "Lab 2:nova setup" better before "Brief interlude: nova evacuate"?

**Comment by aspiers** [comment]
> http://aspiers.github.io/compute-ha-training/#/SOC-demo
> video not available

It's available on my machine, and it's not supposed to be in the git repo anyway.  However I'll probably take out it of the presentation altogether; I just hadn't decided for sure yet.

> http://aspiers.github.io/compute-ha-training/#/starting-point
> screenshot and text outside slide template
> 
> http://aspiers.github.io/compute-ha-training/#/test-vm
> text outside slide template
> 
> http://aspiers.github.io/compute-ha-training/#/shared-storage
> two slides merged, must split "recovery monitor" and "shared storage"

Ah sorry, these are all fixed in my repo but I didn't push them to gh-pages yet.

> Section "Lab 2:nova setup" better before "Brief interlude: nova evacuate"?

No because we need to give Crowbar time to apply not only the Pacemaker barclamp in Lab 1, but all the other OpenStack barclamps leading up to nova.  Again this is addressed in my latest repo.  I'll push shortly.

BTW, this issue was filed in compute-ha-presentation not compute-ha-training ;-)
